#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t', 'europe-docker.pkg.dev/coffee-with-rob/platform-ops/platform-ops:latest', '.' ]
#images: 
#  - 'europe-docker.pkg.dev/coffee-with-rob/platform-ops/platform-ops:latest'


steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=europe-docker.pkg.dev/coffee-with-rob/platform-ops/platform-ops:latest
  - --cache=true
  - --cache-ttl=24h