steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-docker.pkg.dev/coffee-with-rob/platform-ops/platform-ops:latest', '.' ]
images: 
  - 'europe-docker.pkg.dev/coffee-with-rob/platform-ops/platform-ops:latest'
