
FROM us-central1-docker.pkg.dev/cloud-workstations-images/predefined/code-oss:latest
ARG TERRAFORM_VERSION=1.6.2

# Install                                                                                                            
# USER root

################################
# Install Terraform
################################

# Download terraform for linux
RUN wget --progress=dot:mega https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

RUN \
	# Unzip
	unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
	# Move to local bin
	mv terraform /usr/local/bin/ && \
	# Make it executable
	chmod +x /usr/local/bin/terraform && \
	# Check that it's installed
	terraform --version && \
	echo "installed terraform"

# Install Kustomize
RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && echo "installed kustomize"


################################
# Install Firebase
################################
RUN curl -sL https://firebase.tools | bash && echo "installed firebase CLI"

################################
# Install gcloud additions
################################
RUN sudo apt-get install google-cloud-sdk-terraform-tools && echo "installed gcloud terrafrom tools"
RUN sudo apt-get install google-cloud-sdk-config-connector && echo "installed gcloud config-connector"

################################
# Setup terminal
################################
# RUN curl -sfL https://direnv.net/install.sh | bash
RUN apt install -y zsh && echo "installed zsh"
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended && echo "installed oh-my-zsh"
COPY zshrc /sapientcoffee/settings/zshrc



# Give back control
# USER root

RUN wget https://open-vsx.org/api/hashicorp/terraform/linux-x64/2.28.2/file/hashicorp.terraform-2.28.2@linux-x64.vsix  && \
unzip hashicorp.terraform-2.28.2@linux-x64.vsix "extension/*" &&\
mv extension /opt/code-oss/extensions/terraform

RUN sudo mkdir -p /sapientcoffee/settings && mkdir -p /sapientcoffee/scripts
# COPY settings.json /sapientcoffee/settings/settings.json
COPY custom.sh /etc/workstation-startup.d/200_custom.sh
RUN chmod +x /etc/workstation-startup.d/200_custom.sh
# COPY custom.sh /sapientcoffee/scripts/custom.sh
# RUN sudo chmod +x /sapientcoffee/scripts/custom.sh
RUN date >/sapientcoffee/scripts/version
 

# bashrc config
# RUN runuser user -c -l "echo 'alias bob=terraform' >> ~/.bashrc"
# RUN echo 'alias ll="ls -lrt"' >> ~/.bashrc
# RUN runuser user -c -l "echo 'if [ ! -f /.sapientcoffee/setup_compete ]; then /sapientcoffee/scripts/custom.sh' >> ~/.bashrc"
# RUN echo '/sapientcoffee/settings/custom.sh"' >> ~/.bashrc

