steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args: [
    "--destination=europe-docker.pkg.dev/coffee-roaster-base/platform-ops/workspace:gitpod",
    "--dockerfile=Dockerfile-gitpod",
    "--cache=true",
    "--cache-ttl=24h"]
  
timeout: '1600s'
