# SapientCoffee .zshrc template

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git terraform skaffold python kube-ps1 golang gcloud)

source $ZSH/oh-my-zsh.sh

# User configuration

export GOBIN=~/go/bin
export PATH=$PATH:$GOBIN

if [[ ! -a cobra-cli ]]; then
    go install github.com/spf13/cobra-cli@latest
fi

if [ ! -f "/home/user/.sapientcoffee" ]; then
  echo "The doesnt file exists."
  /sapientcoffee/scripts/setup.sh
  touch /home/user/.sapientcoffee
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

cd ~/workspace
