steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/codey-builder-image/codey'
  - '-f'
  - 'Dockerfile'
  - '.'

# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
# - name: 'gcr.io/$PROJECT_ID/gcloud'
#   args: ['info']

# # Confirm that auth is piped through correctly.
# - name: 'gcr.io/$PROJECT_ID/gcloud'
#   args: ['builds', 'list']

images:
- 'europe-docker.pkg.dev/$PROJECT_ID/codey-builder-image/codey'

timeout: 2400s