steps:
  # Build the image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    dir: 'cloud-builder-geminicli'
    args:
      - 'build'
      - '--tag=us-docker.pkg.dev/coffee-plantation/cloud-build-builder/gemini-builder:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Smoke test: check version
  - name: 'us-docker.pkg.dev/coffee-plantation/cloud-build-builder/gemini-builder:latest'
    id: 'smoke-test-gemini'
    dir: 'cloud-builder-geminicli'
    env: ['HOME=/gemini-config']
    args: ['--version']

images:
  - 'us-docker.pkg.dev/coffee-plantation/cloud-build-builder/gemini-builder:latest'

timeout: '1200s'
